### PR TITLE
(DI-252) Update dnf.prov to pick available python intepreter

### PR DESCRIPTION
**Pull request by johnmccabe**
This commit updates the DNF provider so that it works on systems with only `/usr/bin/python3` available (fedora23+).

### CODE REVIEW

**Comment by johnmccabe** [comment]
I've not come across any yum-based distros that are lacking python yet so have not updated that provider.

**Comment by johnmccabe** [comment]
@lutter I've broken this into a shell wrapper and python script as suggested, see the last commit for the reason behind the naming of the python implementation.

I can squash these commits when you're happy.

**Comment by garethr** [comment]
@johnmccabe:

> I've not come across any yum-based distros that are lacking python

Yum is written in Python :)

The very rare exception is probably [tdnf](https://github.com/vmware/tdnf) which is used in VMware Photon and is a native implementation of dnf.

**Comment by johnmccabe** [comment]
@garethr I understood that DNF is in the process of porting to C

**Comment by johnmccabe** [comment]
@lutter can you confirm that the failure you were seeing was:
```
TypeError: can only concatenate list (not "dict_values") to list
```
I'm seeing that on all Fedora revisions and its down to the `absent.values()` returning a view rather than a concrete list.

For Python 2.7+ you can just wrap this in a list() (example output below), for 2.6 you'd need to iterate over the dict (I'm not aware of any distro using DNF with python2 tho???). You be happy with the list() fix?

Also, the current python implementation of the dnf provider would result in a get (for all packages) returning both installed and available - looking at the other providers they just return installed.

Am I right in thinking there is another bug here?

```
$ for i in "${distro[@]}"; do echo "==== ${i} ===="; docker run --rm -ti -v ${PWD}:/libral ${i} /libral/ral/bin/ralsh package kernel; done
==== fedora:23 ====
package::dnf { 'kernel':
  ensure => 'absent',
}
==== fedora:24 ====
package::dnf { 'kernel':
  ensure => 'absent',
}
==== fedora:25 ====
package::dnf { 'kernel':
  ensure => 'absent',
}
==== fedora:26 ====
package::dnf { 'kernel':
  ensure => 'absent',
}
```

**Comment by lutter** [comment]
@johnmccabe I assume when you said "I'm not aware of any distro using DNF with python2 tho" you meant Python 2.6 (F25 has Python 2.7)

Yes, the TypeError was the error I was seeing, and I am fine with a fix that works for Python 2.7+.

I think your test is fine - containers don't have kernels installed in general ;) You should retry it with glibc.
There is a problem though that the provider now dumps all packages, even uninstalled ones. Looks like that was introduced in 17d0ab75. I'll file an issue for that.

**Comment by johnmccabe** [comment]
@lutter I've fixed both the list concatenation and also the handling of absent above. That *should* be us good with the DNF provider now.

I've check the following on fedora 23-26:
- `ralsh package` - returns all non-absent packages on the system
- `ralsh package kernel` - returns `ensure => 'absent'`
- `ralsh package bash` - returns `ensure => '4.3.43-4.fc25'`

**Comment by johnmccabe** [comment]
This addresses #47

**Comment by lutter** [comment]
Awesome !

**Pull request merged**
