### PR TITLE
Add libral bindings for CRuby

### PR DESCRIPTION
**Pull request by lutter**

### CODE REVIEW

**Comment by lutter** [comment]
@garethr since you asked, I updated this PR and am now reasonably happy with how it builds. I'd be fine with merging it now, though would appreciate if somebody would give it a quick spin first

**Comment by garethr** [comment]
I tried building this but ran into a few problems.

* Missing packages - it looks like the f25 image (and instructions) are missing `ruby-devel` and `redhat-rpm-config` from the packages list
* The instructions are missing reference to required gems in the local Ruby I think. I think the following are required, the first one based on the hint in the Travis config:

```
RUN gem install bundler -v 1.12.5 && \
    gem install yard rake-compiler
```

* The build fails to run for the `all` target, with the following output:

```
 make all
[ 65%] Built target libprojectsrc
[ 68%] Built target mruby
[ 71%] Built target libral
g++: error: /usr/src/libral/build/lib/libral.so: No such file or directory
Makefile:255: recipe for target 'libral.so' failed
gmake[3]: *** [libral.so] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/gmake...]
/usr/local/share/gems/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:166:in `block (2 levels) in define_compile_tasks'
/usr/local/share/gems/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:165:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-linux => compile:libral:x86_64-linux => copy:libral:x86_64-linux:2.3.3 => /usr/src/libral/build/ruby/tmp/x86_64-linux/libral/2.3.3/libral.so
(See full trace by running task with --trace)
ruby/CMakeFiles/ruby_compile.dir/build.make:57: recipe for target 'ruby_compile' failed
make[2]: *** [ruby_compile] Error 1
CMakeFiles/Makefile2:480: recipe for target 'ruby/CMakeFiles/ruby_compile.dir/all' failed
make[1]: *** [ruby/CMakeFiles/ruby_compile.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Running with trace and the task mentioned above:

```
$ make ruby_compile --trace
Makefile:348: target 'cmake_check_build_system' does not exist
/usr/bin/cmake -H/usr/src/libral -B/usr/src/libral/build --check-build-system CMakeFiles/Makefile.cmake 0
Makefile:292: update target 'ruby_compile' due to: cmake_check_build_system
make -f CMakeFiles/Makefile2 ruby_compile
CMakeFiles/Makefile2:546: target 'cmake_check_build_system' does not exist
/usr/bin/cmake -H/usr/src/libral -B/usr/src/libral/build --check-build-system CMakeFiles/Makefile.cmake 0
CMakeFiles/Makefile2:487: update target 'ruby/CMakeFiles/ruby_compile.dir/rule' due to: cmake_check_build_system
/usr/bin/cmake -E cmake_progress_start /usr/src/libral/build/CMakeFiles 0
make -f CMakeFiles/Makefile2 ruby/CMakeFiles/ruby_compile.dir/all
CMakeFiles/Makefile2:480: target 'ruby/CMakeFiles/ruby_compile.dir/all' does not exist
make -f ruby/CMakeFiles/ruby_compile.dir/build.make ruby/CMakeFiles/ruby_compile.dir/depend
ruby/CMakeFiles/ruby_compile.dir/build.make:70: target 'ruby/CMakeFiles/ruby_compile.dir/depend' does not exist
cd /usr/src/libral/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /usr/src/libral /usr/src/libral/ruby /usr/src/libral/build /usr/src/libral/build/ruby /usr/src/libral/build/ruby/CMakeFiles/ruby_compile.dir/DependInfo.cmake --color=
make -f ruby/CMakeFiles/ruby_compile.dir/build.make ruby/CMakeFiles/ruby_compile.dir/build
ruby/CMakeFiles/ruby_compile.dir/build.make:57: update target 'ruby_compile' due to: ruby/CMakeFiles/ruby_compile.dir/build.make
cd /usr/src/libral/ruby && rake -s -f /usr/src/libral/build/ruby/Rakefile compile
Makefile:255: update target 'libral.so' due to: libral.o Makefile
: linking shared-object libral/libral.so
rm -f libral.so
g++ -shared -o libral.so libral.o -L. -L/usr/lib64 -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic /usr/src/libral/build/lib/libral.so  -m64  -lruby  -lpthread -ldl -lcrypt -lm   -lc
g++: error: /usr/src/libral/build/lib/libral.so: No such file or directory
Makefile:255: recipe for target 'libral.so' failed
gmake[4]: *** [libral.so] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/gmake...]
/usr/local/share/gems/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:166:in `block (2 levels) in define_compile_tasks'
/usr/local/share/gems/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:165:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-linux => compile:libral:x86_64-linux => copy:libral:x86_64-linux:2.3.3 => /usr/src/libral/build/ruby/tmp/x86_64-linux/libral/2.3.3/libral.so
(See full trace by running task with --trace)
ruby/CMakeFiles/ruby_compile.dir/build.make:57: recipe for target 'ruby_compile' failed
make[3]: *** [ruby_compile] Error 1
CMakeFiles/Makefile2:480: recipe for target 'ruby/CMakeFiles/ruby_compile.dir/all' failed
make[2]: *** [ruby/CMakeFiles/ruby_compile.dir/all] Error 2
CMakeFiles/Makefile2:487: recipe for target 'ruby/CMakeFiles/ruby_compile.dir/rule' failed
make[1]: *** [ruby/CMakeFiles/ruby_compile.dir/rule] Error 2
Makefile:292: recipe for target 'ruby_compile' failed
make: *** [ruby_compile] Error 2
```

Would appreciate some tips here as this could also be user error.

**Comment by lutter** [comment]
None of these were user error - you were totally right about the missing dependencies. I've now updated `HACKING.md`, `Dockerfile.f25`, and `image.sh` to pull in these dependencies from the corresponding rpm's.

The big compilation error was because I had screwed up the dependency between the ruby extension and `libral.so` (it went in the wrong direction) I updated that in `ruby/CMakeLists.txt`.

I just built myself a new libral/f25 container (with `make -C contrib/docker f25`) and then manually built the `dev/cruby` branch inside that container. That all worked, and I could do the following successfully:

```bash
cd /usr/src/libral/build
./bin/dev irb -rlibral
irb(main):001:0> r = Libral::open
=> #<Libral::Ral:0x0000742ea22928>
irb(main):002:0> p = r.provider("file")
=> #<Libral::Provider:0x0000742ea191e8>
irb(main):003:0> p.get("/etc/motd")
=> [{ /etc/motd:: checksum: mtime, checksum_value: 1469186606, ctime: 2017-06-27T18:03:38+0000, ensure: file, group: 0, mode: 0644, mtime: 2016-07-22T11:23:26+0000, owner: 0, type: file }]
```
at which point I decided that everything worked ;)

I haven't updated the images on hub yet, but we'll need new images for the Travis builds, too, because of the new dependencies.

**Comment by lutter** [comment]
After fixing the problem with not building from PR branches, I've now updated the images for Travis, and everything seems great.

**Pull request merged**
