### PR TITLE
Add container-based build environment

### PR DESCRIPTION
**Pull request by ahenroid**

### CODE REVIEW

**Comment by ahenroid** [comment]
@lutter I don't know if this would be useful or worth merging into the main repository, but I've been using this to build libral and leatherman inside a Docker container, just the non-static build on Fedora.

**Comment by DavidS** [comment]
Helpful things like this usually go into the contrib/ folder. That way people understand that the content is not part of the main thing, and (usually) not as supported.

**Comment by lutter** [comment]
This is great ! I would just stick the Dockerfile into the existing `examples/` folder, and add a comment at the top that people should read `../HACKING.md` for more context.

Out of curiosity, is there a reason why this uses Fedora 24 rather than 25 (latest) ?

**Comment by ahenroid** [comment]
@DavidS @lutter Ah, yes, examples/ is the right place for this. My selection of Fedora 24 was completely arbitrary. I'll bump to 25.

**Comment by ahenroid** [comment]
I moved the Dockerfile to examples/ (now based on Fedora 25) and added a comment pointing back to the updated HACKING.md

**Comment by lutter** [comment]
Thanks ! I hope I didn't screw things up too badly by using the web editor to resolve a conflict in `HACKING.md`. Won't do that again ;)

**Pull request merged**
